### PR TITLE
Adds Dockerfile and Compose

### PR DESCRIPTION
**Pull request by andrefreitas**
I have created a Dockerfile to build an image and a compose with an usage example.

Build the image with:
`make`

Launch a container with:
`docker-compose up -d`

I suggest that you publish this image to https://hub.docker.com/

Please let me know if you found any issue.

### CODE REVIEW

**Comment by aheinze** [comment]
Awesome thanks! But I would prefer to see it in a separate repository. I think it should be pretty easy to extend the make file to download/clone the cockpit repository in the current folder.

**Comment by andrefreitas** [comment]
Hi,
Sure, can you create the repo cockpit-docker ?

**Comment by aheinze** [comment]
Done - https://github.com/aheinze/cockpit-docker + gave you push access

**Comment by andrefreitas** [comment]
Hi Artur, thanks :) I have just pushed the Docker files to that repo.

Now we need to publish the image to Dockerhub. Can we talk by Skype or something?

**Pull request closed without merging**
